[spring-boot-version]
about = 'Spring Boot version'
kind = { ARG = { default = '2.4.2' } }

[spring-cloud-version]
about = 'Spring Cloud version'
kind = { ARG = { default = '2020.0.1' } }

[group]
about = 'artifact group & base package'
short = 'g'
kind = { ARG = { default = 'io.spring.sample' } }

[no-gradle-wrapper]
about = 'do not init Gradle wrapper'
kind = { CMD = { order = 0, default = true, cmd = 'gradle -q wrapper --gradle-version 6.8.2' } }

[test]
about = 'executes tests'
kind = { CMD = { order = 1, cmd = './gradlew check' } }

[run]
about = 'runs the application'
kind = { CMD = { order = 1, cmd = './gradlew bootRun' } }
